@startuml

class Solution46{
'attributes
    - map : Map<String, Integer>

'methods
    -printTable(Map<String, Integer> map)
    +countWords() : Map<String, Integer>
    +wordInMap(String word, Map<String, Integer> map) : boolean
}


@enduml